### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by vforvova** [atom/bracket-matcher#101]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.69.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124

TypeError: Cannot read property '0' of null
  at BracketMatcher.module.exports.BracketMatcher.insertText (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:88:56)
  at TextEditor.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:3:61)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:76:20)
  at /Users/vforvova/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:195:15
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1181:26)
  at AutocompleteManager.module.exports.AutocompleteManager.replaceTextWithMatch (/Users/vforvova/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:190:13)
  at AutocompleteManager.replaceTextWithMatch (/Users/vforvova/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.confirm (/Users/vforvova/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:161:6)
  at /Users/vforvova/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at SuggestionList.module.exports.SuggestionList.confirm (/Users/vforvova/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:55:14)
  at SuggestionList.confirm (/Users/vforvova/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:1:1)
  at autocomplete-suggestion-list.SuggestionListElement.confirmSelection (/Users/vforvova/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:85:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at SuggestionList.module.exports.SuggestionList.confirmSelection (/Users/vforvova/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:49:14)
  at autocomplete-suggestion-list.<anonymous> (/Users/vforvova/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:1:1)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:26.1 core:move-right (atom-text-editor.editor.mini)
     -0:25.8 core:move-down (atom-text-editor.editor.mini)
     -0:25.4 core:confirm (atom-text-editor.editor.mini)
     -0:25.4 snippets:available (atom-text-editor.editor.is-focused)
  9x -0:24.0 core:move-down (atom-text-editor.editor.mini)
  4x -0:13.3 core:move-up (atom-text-editor.editor.mini)
  8x -0:11.7 core:move-down (atom-text-editor.editor.mini)
     -0:09.3 core:move-up (atom-text-editor.editor.mini)
     -0:09.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:09.0 core:cancel (atom-text-editor.editor.mini)
     -0:07.0 autocomplete-plus:confirm (input)
     -0:07.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:05.7 core:undo (atom-text-editor.editor.is-focused)
  6x -0:04.6 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.9 autocomplete-plus:confirm (input)
     -0:00.3 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "feedback",
      "metrics",
      "language-php",
      "language-perl",
      "coffee-lint",
      "language-hyperlink",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-gfm",
      "language-c",
      "welcome",
      "language-xml",
      "language-toml",
      "language-property-list",
      "term2",
      "autocomplete-emojis",
      "bookmarks",
      "styleguide",
      "linter-ruby",
      "pomodoro",
      "symbols-view",
      "language-less",
      "data-atom",
      "execute-as-ruby"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
atom-ctags, v2.5.5
atom-lint, v0.20.1
autocomplete-paths, v1.0.0
autocomplete-plus, v2.0.3
autocomplete-snippets, v1.0.0
docblockr, v0.5.8
emmet, v2.3.2
git-log, v0.2.0
language-elixir, v0.3.3
language-go, v0.21.0
language-ruby, v0.47.0
language-slim, v0.3.0
linter, v0.10.1
project-manager, v1.15.5
react, v0.9.7

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Could you please share some reproduction steps if possible?
Also, does the error still occur if you run Atom in safe mode (`atom --safe`)?

**Comment by vforvova** [comment]
It was happened just once, I'll try to reproduce it and then I'll answer you.

**Comment by vforvova** [comment]
There are a lot of deprecations since last update. May it was one of them. Anyway thank you for quick answer!
