### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by nyancat** [atom/bracket-matcher#107]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.178.0
**System**: Mac OS X 10.10.2
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.71.0

### Stack Trace

Uncaught SyntaxError: Unexpected token ILLEGAL

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124

SyntaxError: Unexpected token ILLEGAL
  at TextEditor.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:3:61)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:76:20)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:409:23
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at [object Object].module.exports.React.createClass.onTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:408:30)
  at HTMLDivElement.boundMethod (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)

```

### Commands

```
  9x -8:01.1 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:09.5 core:save (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".DS_Store"
    ],
    "disabledPackages": [
      "vim-mode"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v1.1.0
language-haml, v0.14.0
language-jade, v0.3.0
monokai, v0.9.0
recent-files, v0.3.0
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@maxbrunsfeld Wondering if you have any :thought_balloon: on this one -- any chance this was fixed by https://github.com/atom/text-buffer/pull/58 as well?

**Comment by maxbrunsfeld** [comment]
I think we saw a few issues like this (syntax errors while parsing files from core packages) after `asar` was first introduced. @kevinsawicki do you think this is fixed now?

**Comment by kevinsawicki** [comment]
> do you think this is fixed now?

I do think this has been resolved now, closing this out. Please comment if you still see this happening on Atom 1.0.5+
