### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

### ISSUE THREAD

**Issue by brunoskonrad** [atom/bracket-matcher#144]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.76.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:660

TypeError: Cannot read property 'getTokenIterator' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:660:42)
    at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1135:35)
    at TextEditor.module.exports.TextEditor.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2265:33)
    at TagFinder.module.exports.TagFinder.isRangeCommented (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/tag-finder.js:28:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/tag-finder.js:79:21
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:842:9)
    at TextEditor.module.exports.TextEditor.scanInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2079:26)
    at TagFinder.module.exports.TagFinder.findEndTag (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/tag-finder.js:75:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/tag-finder.js:116:30
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:842:9)
    at TextBuffer.module.exports.TextBuffer.backwardsScanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:853:19)
    at TextEditor.module.exports.TextEditor.backwardsScanInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2083:26)
    at TagFinder.module.exports.TagFinder.findStartEndTags (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/tag-finder.js:102:19)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/tag-finder.js:141:21)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:35)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40:24
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "go-plus",
      "atom-rails"
    ],
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.0
emmet, v2.3.10
language-elixir, v0.5.0
language-lua, v0.9.3
php-twig, v4.0.0
wakatime, v4.0.9

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @brunoskonrad. Can you share more information about what happened here? Can you reliably reproduce this? Do you remember which type of tile you were editing or what you were doing?

**Comment by brunoskonrad** [comment]
@izuzak as I remember I just open a SASS file... And didn't occured again. Sorry can't explain more about that! ):

**Comment by 50Wliu** [comment]
No further reports, closing.
