### ISSUE TITLE
Uncaught Error: Cannot find module 'underscore-plus'

### ISSUE THREAD

**Issue by artivilla99** [atom/bracket-matcher#169]
![screen shot 2015-08-18 at 12 14 30 am](https://cloud.githubusercontent.com/assets/2120159/9322225/256af902-453e-11e5-86c9-6705bab23c39.png)

Steps taken:
1. Downloaded atom editor version 1.0.7 after being recommended by atom to upgrade to help resolve this issue.
2. Same issue on "Cannot find module 'underscore-plus' " is showin gup. Img attached.

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.76.0

### Stack Trace

Uncaught Error: Cannot find module 'underscore-plus'

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/artivilla/.atom/packages/bracket-matcher/lib/bracket-matcher-view.coffee:6:7)
    at Object.<anonymous> (/Users/artivilla/.atom/packages/bracket-matcher/lib/bracket-matcher-view.coffee:382:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
     -0:07.2.0 application:new-file (atom-pane.pane.active)
     -0:05.4.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:01.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "coffee-compile",
      "language-iced-coffee-script",
      "npm-docs",
      "Atom-Syntax-highlighting-for-Sass",
      "coffee-compiler",
      "copy-to-hipchat",
      "travis-ci-status",
      "js2coffee",
      "iced-coffee-compiler",
      "find-letter",
      "find-letter",
      "autocomplete-css",
      "wrap-guide",
      "timecop",
      "linter"
    ],
    "themes": [
      "seti-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.1.0
atom-color-highlight, v3.0.9
atom-material-syntax, v0.2.3
auto-detect-indentation, v0.4.2
auto-update-packages, v1.0.0
autosave, v0.22.0
background-tips, v0.26.0
bezier-curve-editor, v0.7.2
bracket-matcher, v0.76.0
compass, v0.9.1
editor-stats, v0.17.0
figlet, v0.4.0
fuzzy-finder, v0.87.0
git-diff, v0.55.0
javascript-snippets, v1.0.0
language-haml, v0.21.0
language-jade, v0.6.2
language-liquid, v0.4.0
linter-jshint, v1.1.5
meteor-api, v2.20.0
minimap, v4.12.3
resize-indent, v0.2.1
seti-ui, v0.8.0
svg-preview, v0.6.1

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
This package is bundled with Atom, so unless you're developing on the package (in which case you should only link it for dev mode) you should uninstall your manually installed copy.

And your problem is almost definitely caused by not having executed `apm install` from the repo after cloning.
