### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clipScreenColumn' of undefined

### ISSUE THREAD

**Issue by quaritexa** [atom/bracket-matcher#185]
[Enter steps to reproduce below:]

1. Error raised when I paste text to new file on split panel created via Split Diff plugin

**Atom Version**: 1.2.0-beta1
**System**: Mac OS X 10.9.5
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.79.0

### Stack Trace

Uncaught TypeError: Cannot read property 'clipScreenColumn' of undefined

```
At /Applications/Dev/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:770

TypeError: Cannot read property 'clipScreenColumn' of undefined
    at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:867:55)
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:796:19)
    at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/marker.js:177:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/cursor.js:71:26)
    at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1353:35)
    at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2540:44)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Dev/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:111:23)
    at /Applications/Dev/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40:24
    at Emitter.module.exports.Emitter.emit (/Applications/Dev/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Applications/Dev/Atom.app/Contents/Resources/app.asar/src/text-editor.js:211:32
    at Emitter.module.exports.Emitter.emit (/Applications/Dev/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:312:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1251:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1213:19)
    at /Applications/Dev/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
    at Emitter.module.exports.Emitter.emit (/Applications/Dev/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
```

### Commands

```
     -0:40.8.0 blur (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  5x -0:38.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:36.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:36.3.0 split-diff:diffPanes (atom-text-editor.editor.vim-mode-plus.insert-mode)
  8x -0:36.3.0 blur (atom-text-editor.editor.vim-mode-plus.insert-mode)
     -0:29.5.0 core:select-all (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:28.6.0 core:undo (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:26.4.0 core:redo (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:25.7.0 core:select-all (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:25.3.0 core:copy (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  3x -0:24.9.0 blur (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:24.4.0 core:paste (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  5x -0:08.5.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:06.9.0 core:paste (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:04.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "newton-dark-ui",
      "newton-dark-syntax"
    ],
    "disabledPackages": [
      "metrics",
      "vim-mode",
      "quick-jump",
      "save-session"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet",
      "last-cursor-position",
      "multi-cursor",
      "tab-switcher"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.10
atom-alignment, v0.12.1
atom-beautify, v0.28.17
atom-image-resize, v0.3.0
atom-jade, v0.3.0
atom-lorempixel, v0.1.0
atom-vim-colon-command-on-command-pallete, v0.1.0
bezier-curve-editor, v0.7.2
color-picker, v2.0.13
emmet, v2.3.14
file-icon-supplement, v0.8.3
highlight-selected, v0.10.1
jade-beautify, v0.0.11
language-apache, v1.3.0
language-nginx, v0.6.1
last-cursor-position, v0.9.0
linter, v1.10.0
linter-jade, v0.3.2
local-history, v3.2.3
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.4
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
minimap-split-diff, v0.2.1
newton-dark-syntax, v1.1.5
newton-dark-ui, v1.0.9
open-recent, v4.0.1
pigments, v0.18.1
preview-inline, v0.5.1
set-syntax, v0.3.0
split-diff, v0.4.4
table-editor, v0.1.1
ult-terminal, v0.2.0
vim-mode-plus, v0.1.10

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
No further reports, closing.
