### ISSUE TITLE
Uncaught RangeError: Maximum call stack size

### ISSUE THREAD

**Issue by lumean** [atom/bracket-matcher#271]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Unfortunately I can't reproduce this consistently (that's why I can't put the X above).
So far the trigger was to try area-select with alt + mouse drag (Sublime-Style-Column-Selection)
It doesn't happen always, but from my observation, the probability for it to happen grows with the time atom has been running without closing it.

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: MANU-NOTEBOOK
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.85.1

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\decoration.js:62

RangeError: Maximum call stack size exceeded
    at new Decoration (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\decoration.js:62:9)
    at DecorationManager.module.exports.DecorationManager.decorateMarker (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\decoration-manager.js:195:20)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:1704:37)
    at TextEditor.module.exports.TextEditor.addCursor (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2073:12)
    at TextEditor.module.exports.TextEditor.addSelection (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2569:21)
    at C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:64:18
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:392:22)
    at MarkerLayer.module.exports.MarkerLayer.markRange (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:196:19)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:90:62)
    at TextEditor.module.exports.TextEditor.addSelectionForBufferRange (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2254:34)
    at TextEditor.module.exports.TextEditor.createLastSelectionIfNeeded (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2631:21)
    at TextEditor.module.exports.TextEditor.getLastSelection (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2427:12)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\bracket-matcher\lib\bracket-matcher-view.js:73:24)
    at C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\bracket-matcher\lib\bracket-matcher-view.js:3:59
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.addCursor (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2088:20)
    at TextEditor.module.exports.TextEditor.addSelection (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2569:21)
    at C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:64:18
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:392:22)
    at MarkerLayer.module.exports.MarkerLayer.markRange (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:196:19)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:90:62)
    at TextEditor.module.exports.TextEditor.addSelectionForBufferRange (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2254:34)
    at TextEditor.module.exports.TextEditor.createLastSelectionIfNeeded (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2631:21)
    at TextEditor.module.exports.TextEditor.getLastSelection (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2427:12)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (C:\Users\Manuel\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\bracket-matcher\lib\bracket-matcher-view.js:73:24)
```

### Commands

```
     -9:44 editor:toggle-line-comments (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "warnOnLargeFileLimit": 500
  }
}
```

### Installed Packages

```coffee
# User
hex, v0.6.2 (active)
minimap, v4.26.5 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
multi-cursor, v2.1.5 (inactive)
platformio-ide-terminal, v2.2.2 (active)
Remote-FTP, v0.9.4 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
symbols-list, v2.3.5 (active)
sync-settings, v0.8.1 (active)
tree-view-git-status, v1.3.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (active)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by jkeen** [comment]
I too am getting this error after updating some atom packages (didn't pay too much attention to which ones, unfortunately, I just hit the update button).

This is some sort of interaction between this plugin and the [sublime style column selection](https://atom.io/packages/sublime-style-column-selection) plugin. It happens every time I try to use the column selection plugin.

To reproduce:

1. Open a file
2. Try to select a column of text (option click + drag)
3. Experience infinite loop/maximum stack size error

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.85.1


### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86

RangeError: Maximum call stack size exceeded
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:65)
    at DisplayMarker.module.exports.DisplayMarker.onDidDestroy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:63:27)
    at new Decoration (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration.js:58:50)
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:195:20)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1704:37)
    at TextEditor.module.exports.TextEditor.addCursor (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2077:12)
    at TextEditor.module.exports.TextEditor.addSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2569:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:64:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:392:22)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:19)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62)
    at TextEditor.module.exports.TextEditor.addSelectionForBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2254:34)
    at TextEditor.module.exports.TextEditor.createLastSelectionIfNeeded (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2631:21)
    at TextEditor.module.exports.TextEditor.getLastSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2427:12)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:73:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:59
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.addCursor (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2088:20)
    at TextEditor.module.exports.TextEditor.addSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2569:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:64:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:392:22)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:19)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62)
    at TextEditor.module.exports.TextEditor.addSelectionForBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2254:34)
    at TextEditor.module.exports.TextEditor.createLastSelectionIfNeeded (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2631:21)
    at TextEditor.module.exports.TextEditor.getLastSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2427:12)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:73:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:59
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.addCursor (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2088:20)
    at TextEditor.module.exports.TextEditor.addSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2569:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:64:18

	
[repeats many many many many many times]

    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.addCursor (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2088:20)
    at TextEditor.module.exports.TextEditor.addSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2569:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:64:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:392:22)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:19)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62)
    at TextEditor.module.exports.TextEditor.addSelectionForBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2254:34)
    at TextEditor.module.exports.TextEditor.createLastSelectionIfNeeded (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2631:21)
    at TextEditor.module.exports.TextEditor.getLastSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2427:12)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:73:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:59
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.addCursor (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2088:20)
    at TextEditor.module.exports.TextEditor.addSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2569:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:64:18

[/repeat]


    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:425:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:366:12)
    at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:146:19)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:146:32)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:154:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:668:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:65:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:214:26
    at Selection.module.exports.Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:972:7)
    at Selection.module.exports.Selection.selectToScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:201:19)
    at TextEditor.module.exports.TextEditor.selectToScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2283:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:739:31
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:879:15
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:339:11
```

### Commands

```
     -0:23.3.0 settings-view:open (input.hidden-input)
  3x -0:12.1.0 editor:newline (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-terminal",
      "run-command",
      "rspec-snippets",
      "rspec",
      "rails-rspec",
      "ember-cli-helper"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
ariake-dark-syntax, v0.1.1 (inactive)
atom-alignment, v0.12.1 (active)
atom-beautify, v0.29.16 (inactive)
atom-handlebars, v1.3.0 (active)
atom-material-syntax, v0.4.8 (inactive)
atom-material-ui, v1.3.9 (inactive)
atom-qunit-snippets, v1.1.0 (active)
atom-terminal, v0.8.0 (inactive)
atom-ternjs, v0.16.1 (inactive)
atom-wrap-in-tag, v0.6.0 (inactive)
autoprefixer, v3.6.0 (inactive)
chester-atom-syntax, v0.1.1 (inactive)
color-picker, v2.2.4 (active)
css-snippets, v1.1.0 (active)
ember-cli-helper, v0.9.0 (inactive)
ember-tabs, v2.4.1 (active)
git-log, v0.4.1 (active)
git-plus, v7.1.0 (active)
git-time-machine, v1.5.4 (inactive)
Handlebars, v1.7.0 (active)
hydra-syntax-theme, v2.0.4 (inactive)
jshint, v1.8.6 (active)
lines, v0.13.1 (inactive)
linter, v1.11.21 (active)
linter-csslint, v1.3.3 (active)
merge-conflicts, v1.4.4 (active)
monokai, v0.18.0 (inactive)
nucleus-dark-ui, v0.10.22 (inactive)
pigments, v0.38.0 (active)
pretty-json, v1.6.1 (active)
project-manager, v3.3.3 (active)
project-switcher, v0.3.0 (inactive)
qolor, v0.4.1 (active)
rails-rspec, v0.3.2 (inactive)
remote-atom, v1.3.10 (active)
rspec, v0.3.2 (inactive)
rspec-snippets, v0.4.0 (inactive)
run-command, v0.3.2 (inactive)
seti-ui, v1.4.0 (inactive)
snippets, v1.0.5 (active)
sort-lines, v0.14.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
svg-preview, v0.11.0 (active)
Termrk, v0.3.1 (inactive)
textmate-clipboard, v0.3.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
unity-ui, v2.1.8 (inactive)
wakatime, v6.0.12 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.5 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment]
I can reproduce this when using <kbd>Alt</kbd> and left mouse click to select text with the `Sublime-Style-Column-Selection` installed. When testing I only had the `Sublime-Style-Colum-Selection` package installed when testing. In safe mode I do not see this issue.

![sublime-callstack](https://cloud.githubusercontent.com/assets/1058982/21953966/2bf20250-da45-11e6-8e7a-92a4ebe3fdc4.gif)

**Comment by BenLeggiero** [comment]
I get this, too, when holding alt and dragging to use [sublime-style-column-selection](https://atom.io/packages/Sublime-Style-Column-Selection)

**Comment by jkeen** [comment]
I'm back up and running now, and I'm not quite sure what did it… but I can tell you what I did.

I went through my packages and removed the ones I wasn't using, namely `git-time-machine`, and `Termrk`, and then I *uninstalled* `sublime-style-column-selection` and reinstalled it. 

Then I rebooted Atom and… I'm in business. I don't know if this will help y'all, since it didn't look like @lumean had those packages I uninstalled. But thought it was worth updating this thread with the status.

**Comment by BenLeggiero** [comment]
This seems to be linked with trying to select a column on an empty line; it still works fine for me when I don't do that

**Comment by ungb** [comment]
For me I am able to repro, also my Atom editor crashes.  
### atom --version

```
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
### apm --version

```
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.10.1
```

### Community packages
```
Community Packages (1) /Users/bungdonuts/.atom/packages
└── Sublime-Style-Column-Selection@1.7.2

```


Repro:  (using Atom 1.13.0
1. Delete or mv .atom folder.
2.  Open atom and install sublime-style-column-selection
3.  Open a cson file and click alt and do a selection.

![atomcrash](https://cloud.githubusercontent.com/assets/5624870/22211599/661dad54-e142-11e6-8851-2cb3c3aa9b8c.gif)


crash report:
[Atom Helper_2017-01-23-075421_ungb-2020.crash.zip](https://github.com/atom/bracket-matcher/files/724217/Atom.Helper_2017-01-23-075421_ungb-2020.crash.zip)

**Comment by ungb** [comment]
this started failing as of `83d6059a12c16983fe3489ca023911cb1d2f77e0` (Bracket-Matcher 0.83.0).  I went back every release until I stopped seeing the issue.  


![image](https://cloud.githubusercontent.com/assets/5624870/22212433/95ec618a-e145-11e6-9ad0-6c76c7e9ac2c.png)
 

I can't repro this in 0.82 which comes with 1.12.9.

**Comment by as-cii** [comment]
Thanks everyone for the reports and apologies for this regression. A fix for this issue will land in the next Atom stable and beta releases, which should be published later this week.
