### ISSUE TITLE
Can't run tests, trying to contribute

### ISSUE THREAD

**Issue by lacostenycoder** [atom/bracket-matcher#285]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Trying to run the test suite on a package before trying to contribute to it.
Tests won't run and throw error.

### Steps to Reproduce
1. cloned the repo, 
2. cd into local root of cloned package
3. from terminal: `atom .`
4. click `View > Develper > Run Package Specs`
5. get console error:

```
index.js:56 Error: Module version mismatch. Expected 49, got 51.
  at Error (native)
  at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
  at Object.Module._extensions..node (module.js:583:18)
  at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
  at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/node_modules/oniguruma/src/oniguruma.js:1:114)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
  at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/node_modules/first-mate/lib/grammar.js:10:10)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/node_modules/first-mate/lib/grammar.js:384:4)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
  at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/node_modules/first-mate/lib/grammar-registry.js:12:13)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/node_modules/first-mate/lib/grammar-registry.js:268:4)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
  at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/node_modules/first-mate/lib/first-mate.js:4:22)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/node_modules/first-mate/lib/first-mate.js:8:4)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
  at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/lib/selector-cache.coffee:1:17)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/lib/selector-cache.coffee:1:1)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
  at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/lib/tag-finder.coffee:3:17)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/lib/tag-finder.coffee:1:1)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
  at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/spec/close-tag-spec.coffee:1:13)
  at Object.<anonymous> (/Users/lacoste/dev/open_source/atom_packages/bracket-matcher/spec/close-tag-spec.coffee:1:1)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
  at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at requireSpecs (/Applications/Atom.app/Contents/Resources/app.asar/spec/jasmine-test-runner.js:94:9)
  at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/spec/jasmine-test-runner.js:47:7)
  at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-test-window.js:86:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:76:12)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:9)
```
**Expected behavior:**  Test should run and pass

**Actual behavior:**  Error raised see above steps ^^

**Reproduces how often:** 100

### Versions

```
 % atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

% apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.10.2
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Did you `apm install` after cloning the package?  That isn't listed in your reproduction steps.

**Comment by lacostenycoder** [comment]
@50Wliu I tried running that.  Same result.

**Comment by 50Wliu** [comment]
Can you try:
1. Delete the repo (start from fresh)
2. Clone repo
3. cd to repo directory
4. `apm install` in repo directory
5. `atom --test spec`
and see if that works?
