### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ungb** [atom/bracket-matcher#289]
I am not certain how I got this issue as I can't repro again.

I know what I did was I open a file and tried to change the line ending from CRLF to LF, but after trying to repro again, I couldn't.   

/cc @jasonrudolph as I was testing your changes in pr https://github.com/atom/atom/pull/14695.  If this stack trace doesn't look like any thing wrong occurred, we can probably close this issue out until we get more reports.

**Atom**: 1.19.0-dev-e1719a892 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:453

TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:453:35)
    at BracketMatcherView.module.exports.BracketMatcherView.findCurrentPair (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:289:50)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:110:25)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1421:28)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:876:20)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:553:27)
    at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:493:25)
    at setLineEnding (/packages/line-ending-selector/lib/main.js:177:12)
    at Object.didConfirmSelection (/packages/line-ending-selector/lib/main.js:27:13)
    at SelectListView.confirmSelection (/packages/encoding-selector/node_modules/atom-select-list/src/select-list-view.js:296:20)
    at SelectListView.didClickItem (/packages/encoding-selector/node_modules/atom-select-list/src/select-list-view.js:211:10)
    at ListItemView.onclick (/packages/encoding-selector/node_modules/atom-select-list/src/select-list-view.js:151:31)
    at ListItemView.didClick (/packages/encoding-selector/node_modules/atom-select-list/src/select-list-view.js:344:10)
```

### Commands

```
     -1:00.5.0 application:reopen-project (input.hidden-input)
  2x -0:25 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:20.5.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```

```

**Comment by jasonrudolph** [comment]
> @jasonrudolph as I was testing your changes in pr atom/atom#14695. If this stack trace doesn't look like any thing wrong occurred, we can probably close this issue out until we get more reports.

@ungb: I looked at the stack trace, and it doesn't _seem_ related to atom/atom#14695. 🤞
