### ISSUE TITLE
Failed to activate the bracket-matcher package

### ISSUE THREAD

**Issue by FaruqRahmadani** [atom/bracket-matcher#306]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0

### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:717:15)
    at Object.activate (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -0:09.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
blade-snippets 0.2.0 
emmet 2.4.3 
file-icons 2.1.10 
language-blade 0.34.0 
platformio-ide-terminal 2.5.5 
Remote-FTP 1.1.3 
remote-sync 4.1.5 
```

**Comment by maheee** [comment]
Same problem here. No Non-Core Packages.

I've installed Atom yesterday where everything was fine. Win 10 ran an update today and since then it seems to be broken.

---

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:717:15)
    at Object.activate (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/atom-environment.js:843:36
```

### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At C:\Users\mahe\AppData\Local\atom\app-1.19.0\resources\app\node_modules\bracket-matcher\lib\tag-finder.js:55

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (~/AppData/Local/atom/app-1.19.0/resources/app/src/tokenized-buffer.js:252:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (~/AppData/Local/atom/app-1.19.0/resources/app/src/tokenized-buffer.js:246:27)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/tokenized-buffer.js:206:32
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/underscore/underscore.js:666:53
```

**Comment by bcruddy** [comment]
**Atom**: 1.19.0 x64 (apm 1.18.2)
**Electron**: ?
**OS**: MacOS Sierra 10.12.6
**Thrown From**: bracket-matcher package 0.86.0

**Non-core packages:**
├── atom-easy-jsdoc@4.12.1
├── atom-ternjs@0.18.3
├── editorconfig@2.2.2
├── go-debug@1.5.0
├── go-plus@5.5.5
├── go-signature-statusbar@1.2.1
├── hyperclick@0.1.3
├── language-dotfiles@1.1.0
├── language-pug@0.0.21
└── tabs-to-spaces@1.0.3

**Stacktrace:**

```
TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:717:15)
    at Object.activate (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

**Comment by vivirishe** [comment]
Same

**Comment by vivirishe** [comment]
Same problem here:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at /Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/workspace.js:717:15)
    at Object.activate (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
  3x -2:33.5.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
autosave-plus 0.6.0 
color-picker 2.2.5 
emmet 2.4.3 
erb-helper 1.1.0 
highlight-selected 0.13.1 
minimap 4.29.6 
open-in-browsers 0.0.30 
open-recent 5.0.0 
pigments 0.40.2 
react 0.16.2 
seti-ui 1.9.0 
Sublime-Style-Column-Selection 1.7.4 
tree-ignore 0.6.2 
white-cursor 0.7.0 
```

**Comment by 50Wliu** [comment]
Duplicate of #292.

**Comment by MaryAddams** [comment]
So how did we fix it?

**Comment by Ben3eeE** [comment]
@MaryAddams The fix will be released with the next Atom hotfix release.

**Comment by campside** [comment]
go go go

**Comment by matt3224** [comment]
Still got it on 1.20.0-beta2

**Comment by Ben3eeE** [comment]
@matt3224 please open a new issue so we can investigate.

**Comment by matt3224** [comment]
You should reopen this issue as its the same, here's the info:

    Failed to activate the bracket-matcher package

    Cannot read property 'openScopes' of undefined

    TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:125:41)
    at BracketMatcherView.updateMatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:89:18)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:725:15)
    at Object.activate (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:843:36

    The error was thrown from the bracket-matcher package. This issue has already been reported.

**Comment by Ben3eeE** [comment]
@matt3224 There are more details in the full error report that helps us narrow down the problem which is why I asked you to open a new issue. It includes OS information, which package version you are on, currently installed packages, Atom and Electron versions.

**Comment by SwaroopH** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0-beta2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.87.0


### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:125:41)
    at BracketMatcherView.updateMatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:89:18)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:725:15)
    at Object.activate (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
language-babel 2.66.0 
react 0.16.2 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by ungb** [comment]
Hey guys,  My apologies for those on beta.  We missed cherry-picking this into beta when we did the hotfix releases and only :arrow_up: the version in stable.  The hotfix for beta release should go out very soon.  

This should be fixed on beta with https://github.com/atom/atom/commit/69b63cc049ac9ff945831c70fbcaf5c51e915741.

**Comment by nwautier** [comment]
Just got this error today for the first time.  Only unique thing I can think of is that I have implemented the Git and GitHub packages since the last successful run of the software.  Error thrown on startup.

**Comment by IvyMic** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (/opt/atom/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (/opt/atom/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/opt/atom/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/opt/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (/opt/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (/opt/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at /opt/atom/resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (/opt/atom/resources/app/src/workspace.js:717:15)
    at Object.activate (/opt/atom/resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app/src/package.js:253:25)
    at /opt/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:99:21)
    at /opt/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/opt/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:645:40)
    at /opt/atom/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/opt/atom/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app/src/package-manager.js:603:52)
    at /opt/atom/resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by laurmurclar** [comment]
### Steps to Reproduce
```bash
$ git clone https://github.com/atom/bracket-matcher
$ cd bracket-matcher
$ apm link -d
$ atom -d .
```

### Versions
```bash
$ atom --version
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Stack Trace
```
Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:350:52)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/Users/lmc/Code/bracket-matcher/lib/match-manager.coffee:1:5)
    at Object.<anonymous> (/Users/lmc/Code/bracket-matcher/lib/match-manager.coffee:1:1)
    at Object.<anonymous> (/Users/lmc/Code/bracket-matcher/lib/match-manager.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/Users/lmc/Code/bracket-matcher/lib/main.coffee:1:16)
    at Object.<anonymous> (/Users/lmc/Code/bracket-matcher/lib/main.coffee:1:1)
    at Object.<anonymous> (/Users/lmc/Code/bracket-matcher/lib/main.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:47:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:901:29)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:223:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:97:15)
```

All community packages disabled

**Comment by Ben3eeE** [comment]
@laurmurclar You need to run `apm install` in the `bracket-matcher` directory.

See http://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/

**Comment by laurmurclar** [comment]
@Ben3eeE oops, thanks! Is the flight manual the more maintained documentation? I was just following the CONTRIBUTING.md in the `atom/atom` repo.

**Comment by Ben3eeE** [comment]
That seems to be a mistake in the documentation in the CONTRIBUTING.md document. Do you want to open a PR to fix it? 🙂

**Comment by laurmurclar** [comment]
@Ben3eeE already on it 😄 I think it would be better to just link to the more detailed Flight Manual instructions for the relevant section (so they don't have to be maintained in two places)?

**Comment by Ben3eeE** [comment]
Yeah that sounds good to me 🙂 Thank you 🙇

**Comment by BismeetSingh** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Linux Mint
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (/usr/share/atom/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (/usr/share/atom/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/usr/share/atom/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/usr/share/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (/usr/share/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (/usr/share/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at /usr/share/atom/resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:717:15)
    at Object.activate (/usr/share/atom/resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:603:52)
    at /usr/share/atom/resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```

```

bracket match not working.
