### ISSUE TITLE
just atom ask me to do this 

### ISSUE THREAD

**Issue by ZhonglinFeng** [atom/bracket-matcher#316]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0

### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:717:15)
    at Object.activate (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.4.0 
atom-beautify 0.30.5 
emmet 2.4.3 
```

**Comment by Ben3eeE** [comment]
Thanks for reporting this!

This has already been fixed in one of the hotfix releases for Atom 1.19.
