### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by sebastianstemmer** [atom/bracket-matcher#359]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.8
**OS**: "Manjaro Linux"
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.89.2

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:964

TypeError: Cannot read property 'split' of undefined
    at BracketMatcherView.module.exports.BracketMatcherView.isScopeCommentedOrString (/usr/lib/atom/node_modules/bracket-matcher/lib/bracket-matcher-view.js:436:23)
    at BracketMatcherView.module.exports.BracketMatcherView.findMatchingStartPair (/usr/lib/atom/node_modules/bracket-matcher/lib/bracket-matcher-view.js:213:41)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/usr/lib/atom/node_modules/bracket-matcher/lib/bracket-matcher-view.js:99:32)
    at /usr/lib/atom/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:59
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:27:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:156:28)
    at TextEditor.selectionRangeChanged (/usr/lib/atom/src/text-editor.js:3485:18)
    at Selection.markerDidChange (/usr/lib/atom/src/selection.js:1041:17)
    at Selection.marker.onDidChange.e (/usr/lib/atom/src/selection.js:21:39)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:27:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:156:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/usr/lib/atom/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /usr/lib/atom/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:27:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:156:28)
    at Marker.module.exports.Marker.emitChangeEvent (/usr/lib/atom/node_modules/text-buffer/lib/marker.js:441:20)
    at Marker.module.exports.Marker.update (/usr/lib/atom/node_modules/text-buffer/lib/marker.js:374:12)
    at Marker.module.exports.Marker.clearTail (/usr/lib/atom/node_modules/text-buffer/lib/marker.js:196:19)
    at DisplayMarker.module.exports.DisplayMarker.clearTail (/usr/lib/atom/node_modules/text-buffer/lib/display-marker.js:198:32)
    at Selection.clear (/usr/lib/atom/src/selection.js:199:44)
    at Cursor.clearSelection (/usr/lib/atom/src/cursor.js:657:40)
    at Cursor.changePosition (/usr/lib/atom/src/cursor.js:714:10)
    at Cursor.setScreenPosition (/usr/lib/atom/src/cursor.js:67:10)
    at moveCursors.cursor (/usr/lib/atom/src/text-editor.js:2681:46)
    at Array.forEach (<anonymous>)
    at transact (/usr/lib/atom/src/text-editor.js:2871:25)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:957:18)
    at TextEditor.transact (/usr/lib/atom/src/text-editor.js:1997:24)
    at TextEditor.moveCursors (/usr/lib/atom/src/text-editor.js:2870:17)
    at TextEditor.setCursorScreenPosition (/usr/lib/atom/src/text-editor.js:2681:17)
```

### Commands

```
     -1:34.2.0 core:paste (input.hidden-input)
  2x -1:33.7.0 core:save (input.hidden-input)
     -1:23 editor:newline (input.hidden-input)
  4x -1:21.5.0 core:backspace (input.hidden-input)
     -1:14 core:save (input.hidden-input)
  3x -1:09.5.0 core:backspace (input.hidden-input)
     -1:07.8.0 core:save (input.hidden-input)
  2x -1:05.5.0 editor:newline (input.hidden-input)
  5x -1:01.7.0 core:backspace (input.hidden-input)
     -0:58.7.0 core:save (input.hidden-input)
     -0:32.4.0 editor:consolidate-selections (input.hidden-input)
     -0:32.4.0 core:cancel (input.hidden-input)
     -0:30.3.0 editor:newline (input.hidden-input)
  7x -0:25.8.0 core:backspace (input.hidden-input)
     -0:14.2.0 core:copy (input.hidden-input)
  3x -0:04.2.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.8.4 
python-debugger 0.2.0 
```

**Comment by rsese** [comment]
Thanks for the report!

> **Atom**: 1.30.0 x64
> **Electron**: 2.0.8

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
