### ISSUE TITLE
Hello. What can I do to enable tag highlighting with bracket matcher?

### ISSUE THREAD

**Issue by Matiny** [atom/bracket-matcher#372]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hey there! It seems that I've accidentally used a hotkey to disable bracket matcher, but only for HTML files! How can I re-enable it?

### Steps to Reproduce

1. Turn on Atom!
2. Place blinking cursor on HTML tag or use ctrl + m!
3. Notice that it doesn't highlight the opening and closing tag or jump to the closing tag!

**Expected behavior:** I expected the tags to highlight!

**Actual behavior:** Nothing!

**Reproduces how often:** 100%, baby!

### Versions

Version 1.32.2 of Atom!
Typing in apm --version produces this!
Error: spawn UNKNOWN
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at EventEmitter.<anonymous> (C:\Users\Matiny\AppData\Local\atom\app-1.32.2\resources\app\apm\lib\apm-cli.js:169:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

### Additional Information

Not sure, which is why I'm here!!

**Comment by Aerijo** [comment]
> Typing in apm --version produces this!
Error: spawn UNKNOWN
at _errnoException (util.js:1024:11)
at ChildProcess.spawn (internal/child_process.js:323:11)
at exports.spawn (child_process.js:502:9)
at EventEmitter. (C:\Users\Matiny\AppData\Local\atom\app-1.32.2\resources\app\apm\lib\apm-cli.js:169:17)
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)

That's an issue in and of itself.

As for the bracket matching, a new grammar system was introduced that bracket matcher did not handle yet. This has been fixed in master, and will eventually be released to Beta and Stable Atom.

In the mean time, toggling `Settings -> Core -> Use Tree Sitter Parsers` will disable the new grammar and fix your issue.

**Comment by Matiny** [comment]
Thanks, that did it! 👏
