### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined

### ISSUE THREAD

**Issue by jdsimcoe** [atom/bracket-matcher#95]
I get this when trying to undo a commented block of `HTML`code:

```
/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:499
Hide Stack Trace
TypeError: Cannot read property 'tokenAtBufferColumn' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenForPosition (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:499:38)
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:492:22)
  at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1026:35)
  at TextEditor.module.exports.TextEditor.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2374:33)
  at Cursor.module.exports.Cursor.getScopeDescriptor (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:225:26)
  at TagFinder.module.exports.TagFinder.isCursorOnTag (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:39:67)
  at TagFinder.module.exports.TagFinder.findMatchingTags (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:140:16)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:35)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:207:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:302:20)
  at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkersUpdated (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1570:21)
  at /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:595:20)
  at BufferPatch.module.exports.BufferPatch.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/buffer-patch.js:74:21)
  at Transaction.module.exports.Transaction.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/transaction.js:60:29)
  at History.module.exports.History.undo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:84:24)
  at TextBuffer.module.exports.TextBuffer.undo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:675:27)
  at TextEditor.module.exports.TextEditor.undo (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1137:26)
  at TextEditor.atom.commands.add.stopEventPropagation.core:undo (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:304:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:272:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)
```

**Comment by jdsimcoe** [comment]
@nathansobo @kevinsawicki Still getting this error every time I try commenting a block of code in `HTML` and then I hit undo. Any ideas?

**Comment by 50Wliu** [comment]
What Atom version are you using (if it's not 0.173.0+, could you please try updating and then reproducing this error)?  Can you reproduce this in safe mode (`atom --safe`)?

**Comment by jdsimcoe** [comment]
I am on `0.174.0` and I **cannot** reproduce this in safe mode. Commenting and un-commenting via `cmd + /` works normally. How can I isolate what package is causing this?

**Comment by 50Wliu** [comment]
You might want to try [package-cop](https://atom.io/packages/package-cop) which is a package written by @mark-hahn specifically for these things.

**Comment by jdsimcoe** [comment]
Thanks @50Wliu . In the process I updated Color Picker and the problem went away. Strange. Thanks for the help.

**Comment by GabLeRoux** [comment]
I'm having that `Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined` error when having a very long url with a couple of `/`, I hit `cmd+d` until they're all selected, hit enter (did this to see what parts of the url I was having). Once everything is on separate lines, I hit `cmd+z` to revert changes and had this error.

This is marked as closed, but I can repeat each time. I also have `Color Picker` installed, but it's up to date and I always get this error.

### Steps to reproduce
1. `cmd+n` (new tab)
2. Paste this url: `https://github.com/atom/bracket-matcher/issues/95/asdfasdfknasdlkfnad/asdfnasjdnfasd/faskdnfoansdf/asdfknamsodfkn/asdkfnoasd/asdkfnoaisdnfoiqwenf/asdfknasodf/asdfinaosdifa/.sd.fiasdfoihnaosdf/asdfhaosdif/asdfoijasdf`
3. select any `/`
4. hit `/` until they're all select (or hold it)
5. press `enter`
6. `cmd+z`

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.69.0

### Stack Trace

Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:503

TypeError: Cannot read property 'tokenAtBufferColumn' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenForPosition (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:503:38)
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:496:22)
  at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:1044:35)
  at TextEditor.module.exports.TextEditor.scopeDescriptorForBufferPosition (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor.js:2413:33)
  at Cursor.module.exports.Cursor.getScopeDescriptor (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/cursor.js:227:26)
  at TagFinder.module.exports.TagFinder.isCursorOnTag (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:39:67)
  at TagFinder.module.exports.TagFinder.findMatchingTags (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:140:16)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:35)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40:24
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor.js:210:32
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:320:20)
  at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkersUpdated (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:1588:21)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/service-hub/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:599:20)
  at BufferPatch.module.exports.BufferPatch.applyTo (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/buffer-patch.js:74:21)
  at Transaction.module.exports.Transaction.applyTo (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/transaction.js:60:29)
  at History.module.exports.History.undo (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:87:24)
  at TextBuffer.module.exports.TextBuffer.undo (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:679:27)
  at TextEditor.module.exports.TextEditor.undo (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor.js:1172:26)
  at TextEditor.atom.commands.add.stopEventPropagation.core:undo (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-element.js:318:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-element.js:286:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:26.1 editor:move-to-beginning-of-word (atom-text-editor.editor)
  2x -0:25.0 core:move-left (atom-text-editor.editor)
     -0:24.1 editor:move-to-first-character-of-line (atom-text-editor.editor)
     -0:23.9 editor:move-to-end-of-screen-line (atom-text-editor.editor)
  4x -0:23.4 core:move-left (atom-text-editor.editor)
  2x -0:21.6 core:select-all (atom-text-editor.editor)
     -0:18.5 core:close (atom-text-editor.editor)
     -0:15.7 application:new-file (atom-text-editor.editor)
     -0:14.8 core:paste (atom-text-editor.editor.is-focused)
     -0:13.8 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:12.9 core:select-left (atom-text-editor.editor.is-focused)
 21x -0:12.6 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:10.2 refactor:done (atom-text-editor.editor.is-focused)
     -0:10.2 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.7 core:undo (atom-text-editor.editor.is-focused)
     -0:00.2 core:redo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "timecop",
      "vim-mode",
      "symfony-snippets"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ScssBundle, v0.4.0
angularjs, v0.1.0
ascii-codes, v0.3.3
atom-django, v0.2.0
autocomplete-plus, v2.0.6
build, v0.23.3
coffee-lint, v0.7.3
coffee-refactor, v0.6.2
color-picker, v1.4.4
css-snippets, v0.5.0
editorconfig, v0.3.0
grunt-runner, v0.6.0
js-refactor, v0.3.0
language-blade, v0.7.0
language-erlang, v2.0.0
language-gitignore, v0.1.1
language-ini, v1.3.0
language-python-django-templates, v0.1.0
laravel, v0.4.2
laravel-facades, v1.0.0
linter, v0.10.1
linter-pylint, v0.2.0
linter-scss-lint, v0.0.11
linter-xmllint, v0.0.5
minimap, v3.5.6
minimap-git-diff, v3.1.1
refactor, v0.4.1
scope-inspector, v0.2.1
ssh-config, v0.10.0
travis-ci-status, v0.11.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
I just tried reproducing this with minimal packages installed and I **cannot** reproduce using the same exact steps as described on Ubuntu 14.10, Atom 0.176.0.  The only community packages I have installed are file-icons, language-sourcepawn, linter, linter-jshint, and (unreleased) sourcepawn-compiler.

Could you please try to reproduce this in safe mode?

**Comment by GabLeRoux** [comment]
I updated my Packages and problem did not happen again.

`autocomplete-plus@2.0.10`
`minimap@4.0.2`

Sorry, did not test on safemode.
